### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by Iadel95** [ubco-W2022T1-cosc301/project-group06#13]
# Group06 Feedback

Update on the process: we decided to give everybody feedback on their Milestone 3, and then give you all an opportunity to re-submit after applying the feedback. 

There are some items here that will be noted as "for Milestone 5" - for those items, we don't expect you to complete that until Milestone 5.
For **all** other feedback items, you should apply the feedback and resubmit on Gradescope (we will reopen the submission page later this week).

You should take about one week from when you receive your feedback to resubmit your milestone, though this is somewhat flexible. The absolute last day to re-submit Milestone 3 is Nov. 24 at 6 PM (no grace period).

## Group feedback
-Make sure you run a spell check to catch spelling errors, for e.g, this one: https://github.com/jupyterlab-contrib/spellchecker 

- Overall, good job.
### Major Feedback (for Milestone 5)

- Good job

### Minor Feedback
 
 - we are expecting a single analysis file from each member. no need for that combined analysis file and it caused confusion.

 - your method chaining is not done properly, please revise your work.
### Points of Pride
- Good job.
### Major Feedback (for Milestone 5)

- Good job

### Minor Feedback
 
 - we are expecting a single analysis file from each member. no need for that combined analysis file and it caused confusion.

 - your method chaining is not done properly, please revise your work.
### Points of Pride
- Good job.

### Major Feedback (for Milestone 5)

- Good job

### Minor Feedback
 
 - we are expecting a single analysis file from each member. no need for that combined analysis file and it caused confusion.

 - your method chaining is not done properly, please revise your work.
### Points of Pride
- Good job.

**Comment by Existential-Critic** [comment]
What exactly is meant by the method chaining is not done properly? If the code is wrong or not necessary, would that not mean that our analysis pipelines are also incorrect?

While it is appreciated in letting us know we need to revise, this feedback does not really give me any place to start reworking the method chaining save that it is 'wrong'.

**Comment by Iadel95** [comment]
your overall work is good. In the feedback didn't mention a wrong code or unnecessary code. Method chaining is a coding style that is possible with pandas, , in which methods are called on an object sequentially, one after the another.
Please compare your function code with the examples in this link:
https://towardsdatascience.com/using-pandas-method-chaining-to-improve-code-readability-d8517c5626ac
you can Also check the professor's notes and milestone page. 

Best,
Islam Abdelfattah

**Comment by Existential-Critic** [comment]
Got it, thank you!

**Comment by Existential-Critic** [comment]
Completed Milestone 3 fixes
